Enforce the existence of a README.md in branches so that the description shows up in github. We should also work on making sure that it doesn't end up in develop, but that is a bit harder, perhaps.
git-svn-id: https://svn.salilab.org/imp/trunk@15071 e91f8c7b-0e32-4433-a9ac-4502d39a4eab

diff --git a/tools/git/config/hooks/pre-commit b/tools/git/config/hooks/pre-commit
--- a/tools/git/config/hooks/pre-commit
+++ b/tools/git/config/hooks/pre-commit
@@ -15,6 +15,17 @@ else
 	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
 fi
 
+branch=`git status -b| grep "# On branch"| cut -f3 -d\ `
+
+if test "$branch" \!= "develop"
+then
+   if test \! -e README.md
+   then
+       echo "ERROR: Branches that are not develop or master must have a README.md file describing them"
+       exit 1
+   fi
+fi
+
 # Redirect output to stderr.
 exec 1>&2
 files=`git diff-index --name-only $against`
