Make the git hook compain when to try to commit things with untracked files lying around. Annoying at first, but quite nice after a bit.
git-svn-id: https://svn.salilab.org/imp/trunk@16233 e91f8c7b-0e32-4433-a9ac-4502d39a4eab

diff --git a/tools/git/config/hooks/pre-commit b/tools/git/config/hooks/pre-commit
--- a/tools/git/config/hooks/pre-commit
+++ b/tools/git/config/hooks/pre-commit
@@ -32,16 +32,23 @@ then
    fi
 fi
 
-untracked=`git status -u | grep '^# Untracked files:$'`
-if test -n "$untracked"
-then
-  echo "ERROR: There are untracked files in your repository. If you want to keep them around you can add them to your .git/info/exclude file."
-fi
-
 # Redirect output to stderr.
 exec 1>&2
 files=`git diff-index --name-only $against`
 if test -n "$files"
 then
-  exec python ./tools/check-standards.py `git diff-index --name-only $against`
+  if python ./tools/check-standards.py `git diff-index --name-only $against`
+  then
+    echo "Format checks OK."
+  else
+    exit 1
+  fi
+fi
+
+untracked=`git status -u --porcelain | grep '^??'`
+if test -n "$untracked"
+then
+  echo "ERROR: There are untracked files in your repository. If you want to keep them around you can add them to your .git/info/exclude file: " `echo $untracked | cut -f2 -d\ `
+  echo "You can use --no-verify to skip checks if you are sure that is what you want."
+  exit 1
 fi
