minor changes to git scripts
git-svn-id: https://svn.salilab.org/imp/trunk@17408 e91f8c7b-0e32-4433-a9ac-4502d39a4eab

diff --git a/tools/git/config/hooks/pre-commit b/tools/git/config/hooks/pre-commit
--- a/tools/git/config/hooks/pre-commit
+++ b/tools/git/config/hooks/pre-commit
@@ -22,6 +22,12 @@ then
     exit 1
 fi
 
+if test "$branch" == "master"
+then
+    echo "$(tput setaf 1)ERROR: Committing directly to master is not allowed.$(tput sgr0)"
+    exit 1
+fi
+
 if test "$branch" \!= "develop" -a "$branch" \!= "master" -a "$branch" \!= "svn"
 then
    if test \! -e README.md
